apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-frontend-deployment
  labels:
    app: app1-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-frontend
  template:
    metadata:
      labels:
        app: app1-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
