apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team1
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "update", "delete"]
