apiVersion: v1
kind: Pod 
metadata:
  name: quota-pod 
spec:
  containers:
  - name: nginx 
    image: nginx 
    resources:
      requests:
        memory: "500Mi"
        cpu: "300m"
      limits:
        memory: "300Mi"
        cpu: "200m"